### ISSUE TITLE
The global Buffer should no longer be used

### ISSUE THREAD

**Issue by baryon** [astrohackerlabs/earthbucks#1]
The global Buffer should no longer be used; 
[        `const privateKeyHex = Buffer.from(key.privateKey).toString('hex')`
](https://github.com/satored/satored/blob/771b1d1fd000b97d0363f40e9bd4f21ad88509b6/ts/satored-lib/src/main.ts#L16)

instead, the alternative npm buffer should be utilized, which replaces Buffer with Uint8Array. 
https://www.npmjs.com/package/buffer

There is an article explaining why this is the case. 
https://sindresorhus.com/blog/goodbye-nodejs-buffer

Another reason is that Buffer is not available in runtime environments such as React Native and browsers, often leading to confusion in existing codebases. This issue is notably present in bsv1.0/bitcore-lib.

**Comment by ryanxcharles** [comment]
Acknowledged. This is why I mixed Buffer and Uint8Arrays. I like the idea of using this one package instead of mixing the two approaches. I'll aim to use this package.

**Comment by ryanxcharles** [comment]
This has been fixed.
